export const permissionLabels: Record<string, string> = {
  'security.permission.read': '查看权限目录',
  'security.role.read': '查看角色',
  'security.role.write': '管理角色',
  'security.user_role.read': '查看用户角色',
  'security.user_role.write': '管理用户角色',
  'security.effective.read': '预览有效权限',
  'security.audit.read': '查看操作日志',
  'security.audit.export': '导出操作日志',
  'security.audit.archive.download': '下载日志归档',
  'org.company.manage': '管理企业信息',
  'org.department.read': '查看部门',
  'org.department.write': '管理部门',
  'org.user.read': '查看用户',
  'org.user.write': '管理用户',
  'form.definition.read': '查看表单',
  'form.definition.create': '创建表单',
  'form.definition.design': '设计表单与流程',
  'form.definition.publish': '发布与停用表单',
  'form.definition.delete': '删除表单',
  'form.authorization.manage': '管理表单管理员',
  'form.runtime.read': '使用已发布表单',
  'form.data.read': '查看表单数据',
  'form.data.export': '导出表单数据',
  'workflow.instance.start': '发起审批',
  'workflow.instance.read': '查看审批记录',
  'workflow.instance.withdraw': '撤回本人审批',
  'workflow.instance.override': '紧急干预审批',
  'workflow.task.approve': '审批任务',
  'workflow.task.reject': '驳回任务',
  'workflow.task.transfer': '转交任务',
  'workflow.task.delegate': '委托任务',
  'workflow.task.add_assignee': '加签任务',
  'workflow.task.recall': '撤回子任务',
  'workflow.automation.retry': '重试自动化任务',
  'file.upload': '上传附件',
  'file.read': '读取授权附件',
};

export function displayPermissionName(code: string, fallback: string) {
  return permissionLabels[code] ?? fallback;
}
