import type { MobileHistoryItem } from "./tasks.api";

export function TaskTimeline({ history, processSnapshot }: { history: MobileHistoryItem[]; processSnapshot: unknown }) {
  if (history.length === 0) return <p className="muted small">暂无流转记录</p>;
  return <ol className="approval-records__list">{history.map((entry, index) => { const done = entry.action !== "ARRIVE"; return <li key={entry.id} className={`approval-records__item ${done ? "approval-records__item--done" : "approval-records__item--current"}`}><span className="approval-records__marker" /><article className={`approval-record-card${done ? "" : " approval-record-card--current"}`}><div className="approval-record-card__top"><div><span className="approval-record-card__node">{nodeLabel(processSnapshot, entry.toNodeId || entry.fromNodeId)}</span><strong>{entry.operatorId ? `审批人 #${entry.operatorId}` : "系统"}</strong></div><span className={`approval-record-card__status ${done ? "approval-record-card__status--done" : "approval-record-card__status--current"}`}>{actionLabel(entry.action)}</span></div><p>{entry.comment || (index === 0 ? "流程已发起并进入审批。" : "审批节点状态已更新。")}</p><footer><span>{nodeLabel(processSnapshot, entry.fromNodeId)} → {nodeLabel(processSnapshot, entry.toNodeId)}</span><time>{formatDate(entry.createdAt)}</time></footer></article></li>; })}</ol>;
}

function actionLabel(action: string) { return ({ START: "已提交", ARRIVE: "审批中", APPROVE: "已通过", REJECT: "已驳回", WITHDRAW: "已撤回", COMPLETE: "已完成" } as Record<string, string>)[action] ?? action; }
function nodeLabel(snapshot: unknown, nodeId?: string | null): string { if (!nodeId) return "—"; return findNodeName(snapshot, nodeId) ?? nodeId; }
function findNodeName(node: unknown, id: string): string | null { if (!node || typeof node !== "object") return null; const record = node as Record<string, unknown>; if (record.id === id) { const props = record.props as Record<string, unknown> | undefined; return typeof props?.name === "string" ? props.name : typeof record.label === "string" ? record.label : typeof record.name === "string" ? record.name : id; } for (const value of Object.values(record)) { if (Array.isArray(value)) { for (const child of value) { const found = findNodeName(child, id); if (found) return found; } } else if (value && typeof value === "object") { const found = findNodeName(value, id); if (found) return found; } } return null; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { hour12: false, month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }

export default TaskTimeline;
